USE [MasterDb]
GO
  
INSERT INTO [dbo].[DataTable1]
VALUES
 (
concat('DataCol1_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol2_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol3_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol4_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol5_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol6_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol7_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol8_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol9_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol10_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol11_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol12_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol13_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol14_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol15_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol16_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol17_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol18_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol19_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol20_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol21_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol22_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol23_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol24_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol25_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol26_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol27_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol28_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol29_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol30_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol31_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol32_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol33_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol34_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol35_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol36_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol37_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol38_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol39_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol36_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol41_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol42_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol43_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol44_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol45_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol46_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol47_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol48_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol49_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
,concat('DataCol50_',SUBSTRING (REPLACE(CONVERT(VARCHAR(36), NEWID()), '-',''), 1, 10))
 )
GO 2000000


